### ISSUE TITLE
ActiveSync Contacts broken - iOS

### ISSUE THREAD

**Issue by henningwerner** [mail-in-a-box/mailinabox#761] opened 2016-03-18 10:30 UTC
I've try to sync my contacts via ActiveSync on my iPhone with iOS 9.X
But my contacts look like this:
Firstname;Lastname

In my opinion it should be in the right columns now is all in the firstname field but seperated with semi colon. The other thing is the sync is incomplete some contacts are missing.
But alle are visible in ownCloud.

**Comment by yodax** [comment] 2016-03-21 05:42
I did a quick test and can confirm this. If i have some time I will have a look at the cause.

**Comment by yodax** [comment] 2016-03-21 05:51
I checked if using card dav directly would work and it doesn't. Same problem. So it isn't an z-push issue, it is probably an own cloud issue. My contact says LastName;FirstName;;;

Is anybody else using OwnCloud contacts with iOS 9 and not seeing this problem?

**Comment by nstanke** [comment] 2016-03-21 16:48
Everything good here. Though I'm on the latest 9.3 beta using CardDav w/ OwnCloud updated to 8.2.2 through the interface.

**Comment by yodax** [comment] 2016-04-10 12:38
Could you try again with the latest dev version? That has an upgraded own cloud and that works for me.

**Comment by comvice** [comment] 2016-05-06 08:28
@yodax sorry for my late reply.
I now managed it to upgrade to version v0.17c.
Should there the bug fixed or what should I do?

**Comment by yodax** [comment] 2016-05-06 08:52
It worked for me, so it should be fixed. Otherwise wait for own cloud 9.

**Comment by comvice** [comment] 2016-05-06 11:54
Not for me, I first disabled and remove contacts from phone then activated and finally broken contacts are here.

**Comment by henningwerner** [comment] 2016-05-21 13:05
@yodax what you've done?
Do you reimport your contacts or just deactivate and activate the contact switch on your iPhone?
The update to v0.18b also deliver me broken contacts.

**Comment by yodax** [comment] 2016-05-22 14:57
I haven't done anything since the owncloud upgrade. It just worked. I don't have any ideas then. Seems weird. Did you try resyncing the phone from te box' command line using zpush admin? (Long shot)

**Comment by JoshData** [comment] 2017-08-03 12:46
Closing because it's been a while. Feel free to re-open.

**Closed by JoshData** 2017-08-03 12:46 UTC
