### ISSUE TITLE
Status checks crash if the mailinabox.email website is down.

### ISSUE THREAD

**Issue by ChiefGyk** [mail-in-a-box/mailinabox#1062] opened 2017-01-10 04:43 UTC
Whenever I go to check the status on one of the production email servers I get a something is wrong error. When I run it manually this is what I get

`box:~/mailinabox/management$ sudo ./status_checks.py 

System
======
✓  All system services are running.
✓  SSH disallows password-based login.
✓  System software is up to date.
^[[ATraceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 951, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 886, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1268, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./status_checks.py", line 967, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "./status_checks.py", line 60, in run_checks
    run_system_checks(rounded_values, env, output)
  File "./status_checks.py", line 166, in run_system_checks
    check_miab_version(env, output)
  File "./status_checks.py", line 810, in check_miab_version
    latest_ver = get_latest_miab_version()
  File "./status_checks.py", line 797, in get_latest_miab_version
    return re.search(b'TAG=(.*)', urllib.request.urlopen("https://mailinabox.email/setup.sh?ping=1").read()).group(1).decode("utf8")
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
`

**Comment by ChiefGyk** [comment] 2017-01-10 04:47
Seems to also happen on another production server as well. So that makes two completely different servers I run having the same exact issue

`box:~/mailinabox/management$ sudo ./status_checks.py 
[sudo] password for alon: 

System
======
✓  All system services are running.
✓  SSH disallows password-based login.
✓  System software is up to date.
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 951, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 886, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1268, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./status_checks.py", line 967, in <module>
    run_checks(False, env, ConsoleOutput(), pool)
  File "./status_checks.py", line 60, in run_checks
    run_system_checks(rounded_values, env, output)
  File "./status_checks.py", line 166, in run_system_checks
    check_miab_version(env, output)
  File "./status_checks.py", line 810, in check_miab_version
    latest_ver = get_latest_miab_version()
  File "./status_checks.py", line 797, in get_latest_miab_version
    return re.search(b'TAG=(.*)', urllib.request.urlopen("https://mailinabox.email/setup.sh?ping=1").read()).group(1).decode("utf8")
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>
`

**Comment by anoma** [comment] 2017-01-10 09:53
Confirmed here as well.

**Comment by biermeester** [comment] 2017-01-10 11:53
I have the same problem. (I also needed to fiddle with (i.e re-install) pyopenssl after the last update to get everything running smoothly)

**Comment by yodax** [comment] 2017-01-10 13:08
The problem is that the mailinabox.email site is down. The status check therefore times out on requesting https://mailinabox.email/setup.sh?ping=1. This breaks the update check. Once the site is back up it should work again.

**Comment by ChiefGyk** [comment] 2017-01-10 15:13
@yodax thank you for the information, any ETA on when the site will be resolved?

**Comment by yodax** [comment] 2017-01-10 15:24
I don't know. @joshdata hosts the domains.

**Comment by mboersma** [comment] 2017-01-10 16:01
Same issue here. @ChiefGyk if you click the "Disable New-Version Check" link, it will work around the issue for now.

**Comment by acanton77** [comment] 2017-01-10 16:05
This is a minor point of failure. The status check of our mail servers should not be dependent on the maininabox site being up. Perhaps a timeout can be built into the code such that the status script will continue if Josh's site is down.  I killed an hour last night trying to figure out if it was a Linode server issue or a Pair Networks Cloud server issue (testing both server companies... will settle on one or the other eventually) or a local DNS issue or something else. I didn't know that this board existed until now, so thanks for posting the above info.

**Comment by mboersma** [comment] 2017-01-10 16:11
> The status check of our mail servers should not be dependent on the maininabox site being up.

Ideally all other checks would proceed and the "New-Version" check would just say "unable to contact https://mailinabox.email". Right now the web page renders empty and I'm guessing a 500-type code is returned.

**Comment by just4t** [comment] 2017-01-10 16:12
> ... The status check of our mail servers should not be dependent on the maininabox site being up. ...
**+1** for this call here.

**Comment by mboersma** [comment] 2017-01-10 19:09
Just to follow up, the mailinabox URL is accessible again.

**Comment by JoshData** [comment] 2017-01-10 19:34
Yeah everything's back. The hosting provider had a glitch.

Obviously yes this should not happen. If someone can submit a PR to fix this problem, that'd be great.

**Comment by biermeester** [comment] 2017-01-10 23:00
I've pushed an update to my fork, but it looks like some old PRs are messing things up. I'll have another look soon.

The changes are in this commit: https://github.com/biermeester/mailinabox/commit/196350d4306c6498657baea8c2538ffb64f92ef3

**Comment by biermeester** [comment] 2017-01-11 13:04
While trying to fix my mess (reforking Miab etc.), the commit ended up in an old, open pull request: https://github.com/mail-in-a-box/mailinabox/pull/970

I hope this isn't an problem 😄

**Comment by yodax** [comment] 2017-01-14 08:25
I have taken the commit and put it into a PR.

**Comment by JoshData** [comment] 2017-01-15 15:35
Fixed by #1065, thanks @yodax .

**Closed** 2017-01-15 15:56 UTC
