### ISSUE TITLE
Receiving status emails "dovecot is not running"

### ISSUE THREAD

**Issue by maximbaz** [mail-in-a-box/mailinabox#1129] opened 2017-04-01 14:42 UTC
Since March I've started receiving emails status emails about `dovecot` being not running (5 so far). 

```
System -- Previously:
=====================
✓  All system services are running.

System -- Currently:
====================
✖  Dovecot LMTP LDA is not running (port 10026).
✖  IMAPS (dovecot) is not running (port 993).
✖  Mail Filters (Sieve/dovecot) is not running (port 4190).
```

On the next day I always receive email saying that everything is fixed.

```
System -- Previously:
=====================
✖  Dovecot LMTP LDA is not running (port 10026).
✖  IMAPS (dovecot) is not running (port 993).
✖  Mail Filters (Sieve/dovecot) is not running (port 4190).

System -- Currently:
====================
✓  All system services are running.
```

I haven't observed any problems with actually sending and receiving emails. The admin page says that everything is all right. 

This looks to me a lot like #628 (in terms of the check being simply not reliable), but of course I'm more worried if this is an actual issue.

Has anyone else observed this?

**Comment by anoma** [comment] 2017-04-01 15:48
Clicked the -1 thumb to signify i have not seen this.

**Comment by chris13524** [comment] 2017-04-02 12:55
Dovecot "stopped" for me a few weeks ago, but I immediately logged onto the server and restarted it. Haven't had it happen since.

**Comment by JoshData** [comment] 2017-08-03 12:21
This is usually caused by insufficient memory, leading to processes being randomly terminated.

Closing because it's been a while. Feel free to reopen.

**Closed by JoshData** 2017-08-03 12:21 UTC

**Comment by priyaraj-pr** [comment] 2019-02-01 06:07
Im facing Same issue Here Again ..

System
--
✖ | Dovecot LMTP LDA is not running (port 10026).
✖ | IMAPS (dovecot) is not running (port 993).
✖ | Mail Filters (Sieve/dovecot) is not running (port 4190).
✓ | SSH disallows password-based login.
✓ | System software is up to date.
? | You are running version Mail-in-a-Box v0.30. Mail-in-a-Box version check disabled by privacy setting.
✓ | System administrator address exists as a mail alias. [administrator@box.corpacademia.net ↦ admin@corpacademia.net]
✓ | The disk has 793.64 GB space remaining.
✓ | System memory is 94% free.



No able to login to any mails in roundcube  Connection to storage server failed.
Emails are not working
