### ISSUE TITLE
Something went wrong provisioning ssl from lets encrypt

### ISSUE THREAD

**Issue by kaiden1002** [mail-in-a-box/mailinabox#1082] opened 2017-01-25 10:43 UTC
Hi I am unable to provision from lets encrypt I get a generic error I have tried removing the lets encrypt folder so that I can start fresh so to speak but I only ever get the generic error here is my sys log entry for it:

***
Jan 25 05:24:42 droplet Exception on /ssl/provision [POST]#012Traceback (most recent call last):#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise#012    raise value#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "/usr/local/bin/mailinabox-daemon", line 55, in newview#012    return viewfunc(*args, **kwargs)#012  File "/usr/local/bin/mailinabox-daemon", line 384, in ssl_provision_certs#012    jsonable=True)#012  File "/home/tiff/mailinabox/management/ssl_certificates.py", line 272, in provision_certificates#012    import acme.messages#012  File "/usr/local/lib/python3.4/dist-packages/acme/messages.py", line 4, in <module>#012    from acme import challenges#012  File "/usr/local/lib/python3.4/dist-packages/acme/challenges.py", line 9, in <module>#012    import OpenSSL#012ImportError: No module named 'OpenSSL'
***

Let me know if you need more or different info or if you need access to the box it's a personal box for private mail id just like to get it working right and this had never been an issue before

Thanks In advance

**Comment by cromulus** [comment] 2017-01-26 15:48
Duplicate of #1067

**Comment by myfirstnameispaul** [comment] 2017-01-28 17:07
I have the same issue and none of the solutions in #1067 resolves the issue.

See forum post: https://discourse.mailinabox.email/t/lets-encrypt-doesnt-provision-a-certificate/1844

**Comment by kaiden1002** [comment] 2017-01-28 17:09
My issue was with python by removing all open-ssl packages and reinstalling
via pip3 it fixed

Respectfully,

Tiffany Bilgore

**Comment by jalogisch** [comment] 2017-02-20 09:21
please check if this will solve your issue: https://github.com/mail-in-a-box/mailinabox/issues/1101#issuecomment-281026627

**Closed** 2017-08-03 12:25 UTC
