### ISSUE TITLE
Long response from tab “Users” in web-interface Improvements

### ISSUE THREAD

**Issue by Evgeniy-Bondarenko** [mail-in-a-box/mailinabox#851] opened 2016-06-01 12:12 UTC
Preview discussion with screenshot  on page [https://discourse.mailinabox.email/t/long-response-from-tab-users-in-web-interface/1277](https://discourse.mailinabox.email/t/long-response-from-tab-users-in-web-interface/1277)

I have long response from tab "Users" in web-interface, maybe because MIB check size all mailbox.(30-50 users now) But usually need create or update password for users.

**\- can create new button for checking size mailbox, for checking size only when need it**

I am have timeout response from MIB when update user pages in web interface.

Now max-size mailbox is 7Gb, in total all mailbox are ~90G

If this error connecting with size mail-dir - then need create separate button for checking size(_not calculate fir all dir when open page_)

**Comment by aspdye** [comment] 2016-06-01 12:15
Good Point 😉 ...maybe we can bring this into MiaB together with Quota function (sorry @JoshData for mention that agin 😜)

**Comment by yodax** [comment] 2016-06-03 05:28
Also see https://github.com/mail-in-a-box/mailinabox/issues/531 and the discussion about a different mailbox type in: https://github.com/mail-in-a-box/mailinabox/pull/510.

**Comment by marcosms** [comment] 2018-09-03 09:02
I have the same trouble. I have a lot of big mailboxes (110 accounts. Some accounts have a lot of mails (about 15 GB). I'm ussing 289 GB and i have a lot of problems to access to the "users" tab. I notice that the error is a timeout (the error appears after 60 seconds of the click in the "users" tab). I think that there are tho ways to solve this trouble. 

- Increasing the timeout (keepalive). I spend a lot of days searching how to do this. 
- Disallowing the mailbox size checking. 

I will try this second option (if i can see how to do it). If you know how to do it please post it. 

Thanks.

**Comment by marcosms** [comment] 2018-09-03 09:18
I post this trouble here

https://discourse.mailinabox.email/t/speed-of-the-admin-menus/3301/8

If i can see any solution i'll post here.

**Comment by marcosms** [comment] 2018-09-03 10:11
I have posted a little workarround in the forum that i posted in my previous message. 

you have to edit this file

/home/myuseraccount/mailinabox/management/templates/users.html

and comment the following lines: 

`
#      <th>Mailbox Size</th>

#    <td class='mailboxsize'>
#    </td>


#          n.find('.mailboxsize').text(nice_size(user.mailbox_size))

`
This disable the check of the size of the accounts and let you to manage the accounts (erase, make new accounts, etc...).

**Comment by JoshData** [comment] 2018-11-30 14:49
dupe of #531

**Closed by JoshData** 2018-11-30 14:49 UTC
