### ISSUE TITLE
Unable to resolve host box.xxxxx.codes: Resource temporarily unavailable

### ISSUE THREAD

**Issue by theiosdevguy** [mail-in-a-box/mailinabox#1873] opened 2020-11-30 18:37 UTC
Hi Team,

I am trying to host mail in a box on an UpCloud instance. My domain provider is Namecheap. I have followed the guidelines and added the glue records and changed the default nameservers. I have also changed the UpCloud's reverse DNS to box.xxxx.codes. But the script keeps throwing error `Unable to resolve host box.xxxxx.codes: Resource temporarily unavailable. Waiting for the Mail-in-a-Box management daemon to start...`. Looks like the reverse DNS is the problem maybe. When I try to do a `ping box.xxxx.codes` I get Ping could not find host error. Is .codes tld supported by mail in a box?

Also, I did a service mailinabox status and received this

```
root@box:~# service mailinabox status
* mailinabox.service - Mail-in-a-Box System Management Service
   Loaded: loaded (/lib/systemd/system/mailinabox.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-12-01 00:01:10 IST; 2min 56s ago
 Main PID: 6664 (code=exited, status=1/FAILURE)

Dec 01 00:01:10 box.nebula.codes systemd[1]: Started Mail-in-a-Box System Management Service.
Dec 01 00:01:10 box.nebula.codes start[6664]: Traceback (most recent call last):
Dec 01 00:01:10 box.nebula.codes start[6664]:   File "/root/mailinabox/management/daemon.py", line 28, in <module>
Dec 01 00:01:10 box.nebula.codes start[6664]:     for line in f:
Dec 01 00:01:10 box.nebula.codes start[6664]:   File "/usr/local/lib/mailinabox/env/lib/python3.6/encodings/ascii.py", l
Dec 01 00:01:10 box.nebula.codes start[6664]:     return codecs.ascii_decode(input, self.errors)[0]
Dec 01 00:01:10 box.nebula.codes start[6664]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 795:
Dec 01 00:01:10 box.nebula.codes systemd[1]: mailinabox.service: Main process exited, code=exited, status=1/FAILURE
Dec 01 00:01:10 box.nebula.codes systemd[1]: mailinabox.service: Failed with result 'exit-code'.
```

Please suggest

**Comment by hija** [comment] 2020-12-01 21:42
The service is unavailable because mailinabox fails to start. Most probably you did not setup a completely new Ubuntu 18.04 instance, did you?

**Comment by theiosdevguy** [comment] 2020-12-01 21:56
> The service is unavailable because mailinabox fails to start. Most probably you did not setup a completely new Ubuntu 18.04 instance, did you?

Hi @hija It was a complete new Ubuntu 18.04 instance.

**Comment by hija** [comment] 2020-12-01 22:01
This is very strange. Is it the normal Ubuntu 18.04 x64 (server edition)? Not a minimal image or so?

**Comment by theiosdevguy** [comment] 2020-12-01 22:03
> This is very strange. Is it the normal Ubuntu 18.04 x64 (server edition)? Not a minimal image or so?

![image](https://user-images.githubusercontent.com/1865865/100802227-17b91b80-344f-11eb-9923-d0ed22f851bd.png)

Yes. The default from UpCloud

**Comment by theiosdevguy** [comment] 2020-12-01 22:05
@hija It has IPv6 support enabled. Does that matter?

**Comment by hija** [comment] 2020-12-01 22:09
No, not afaik. Did you set a language before or so? Or was the first command you ran the installer script for miab?

**Comment by theiosdevguy** [comment] 2020-12-01 22:11
> No, not afaik. Did you set a language before or so? Or was the first command you ran the installer script for miab?

The first and only command I ran `curl -s https://mailinabox.email/setup.sh | sudo -E bash`

**Comment by ddavness** [comment] 2020-12-03 02:34
looks like this could be a locales issue. is the `locales` package installed?

**Comment by theiosdevguy** [comment] 2020-12-03 06:11
> looks like this could be a locales issue. is the `locales` package installed?

Yes locales-all is installed.

**Comment by hija** [comment] 2020-12-03 11:28
What's the output of the `locale` command?

**Comment by hija** [comment] 2020-12-05 00:42
Okay, I just got myself an Upcloud Instance and did the debugging.
We were on the right track. The locale command shows:

```
LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=

```

This is not enough for python to determine the correct encoding.

**Background**
Jesus, this took me very long to figure out. It turns out, that Upcloud selected "no localization" during installation which leads to en_US.UTF-8 not being set as default language. That would not cause a bug, but the installer sets the default LANG and language to be always C in the /root/.profile:

```
# Installed by Debian Installer:
#  no localization for root because C
#  cannot be properly displayed at the Linux console
LANG=C
LANGUAGE=C
```

This means that all the other attempts to set and generate new locales was useless, because the LANG and LANGUAGE was always reset to C by the .profile-script.

**Fix (@theiosdevguy)**

**Important:** Your miab installation most likely did not finish and very important security settings have not been set (i.e. the firewall). Please **recreate (i.e. delete and redeploy) your instance again**. Before you run the installation, follow these instructions:

* Run the following four command as root (the machine restarts afterwards):
```
locale-gen "en_US.UTF-8"
update-locale LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8"
head -n -5 /root/.profile > /root/.profile
reboot now
```

* Open a new terminal window (i.e. open a new putty window if your on windows, dont reuse the old one)
* Now go through the whole installation again (`curl -s https://mailinabox.email/setup.sh | sudo -E bash`)

@theiosdevguy Please report back if this fixes your problem. If it does not, please provide further information. Otherwise please give us positive feedback so we can close this issue.

@JoshData Do you see a neccessity to implement a locale check into the setup script so we can catch this case? Or do we consider this a corner case? Besides, while installing the installer script hang during 

```
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
Waiting for the Mail-in-a-Box management daemon to start...
```

Maybe @theiosdevguy forgot to mention this, but this is of course already a strong indicator that something is wrong. More importantly, this stops the installation from ending and leaves miab in an incomplete state (e.g. fail2ban not configured, no first user etc.). Maybe one could check if LANG is set to C and abort then?

**Comment by hija** [comment] 2020-12-05 09:52
Relates to #1522 (Although I think you should delete the leftovers of the debian installer, i.e. the cause,  (like I did in the bugfix above) rather than fixing it by overwriting the locales again)

**Comment by JoshData** [comment] 2020-12-06 17:55
The MiaB setup runs `locale-gen "en_US.UTF-8"` at the start, so the problem isn't that. I thought we were setting the environment variables when the daemon starts but that doesn't appear to be the case. I wonder if it was removed at some point.

**Comment by theiosdevguy** [comment] 2020-12-07 15:23
@hija Your suggestion above worked perfectly and I am able to setup the new instance without any error. Thank you very much for a quick resolution.

**Comment by hija** [comment] 2020-12-07 20:38
That's great. I think you can close the issue then.

@JoshData I will have a look into the daemon and will do a PR on using en_US-UTF8 when starting the daemon. :)

**Closed** 2020-12-08 09:57 UTC
