### ISSUE TITLE
DNS checks not parsing :: in IPV6 addresses correctly

### ISSUE THREAD

**Issue by StartersOrders** [mail-in-a-box/mailinabox#907] opened 2016-08-14 20:18 UTC
v0.19 appears to not see the RFC1924'd addresses as the same, e.g.:

1111:2222:3333:0:aaaa:bbbb:cccc:dddd
1111:2222:3333::aaaa:bbbb:cccc:dddd

Are detected as different addresses.

**Comment by Jonchun** [comment] 2016-12-28 01:45
I think this should do it:

#1052

**Comment by sdukhovni** [comment] 2017-07-12 07:38
#1052 fixes the check for the primary box.example.com domain, but not the ones for example.com or www.example.com. I'm still getting errors on those checks on v0.23a because the IPv6 addresses aren't normalized properly.

**Comment by yodax** [comment] 2017-07-12 11:57
Are you able to check if this patch works? I can't reproduce it.

```
diff --git a/management/status_checks.py b/management/status_checks.py
index 42fc876..3ee1c12 100755
--- a/management/status_checks.py
+++ b/management/status_checks.py
@@ -640,7 +640,7 @@ def check_web_domain(domain, rounded_time, ssl_certificates, env, output):
                for (rtype, expected) in (("A", env['PUBLIC_IP']), ("AAAA", env.get('PUBLIC_IPV6'))):
                        if not expected: continue # IPv6 is not configured
                        value = query_dns(domain, rtype)
-                       if value == expected:
+                       if normalize_ip(value) == normalize_ip(expected):
                                ok_values.append(value)
                        else:
                                output.print_error("""This domain should resolve to your box's IP address (%s %s) if you would like the box to serve
```

**Comment by geekafy** [comment] 2017-07-13 02:12
Thanks @yodax, this solved the issue for me!!! 

Had to reboot the server for it to take effect.

Now all IPv6 checks are good! :-)

**Comment by JoshData** [comment] 2017-07-13 11:19
Should be fixed by the PR merged above.

**Closed by JoshData** 2017-07-13 11:19 UTC
