### ISSUE TITLE
Status Checks Change Notice every day

### ISSUE THREAD

**Issue by frootmig** [mail-in-a-box/mailinabox#725] opened 2016-02-20 12:47 UTC
I get every day an email with
Subject: Status Checks Change Notice
Body:
System -- Added
===============

**Comment by smic77** [comment] 2016-02-22 19:19
Quite the same here... 

I receive each day at 3 AM a mail entitled "[box.XXXX.XX] Status Checks Change Notice". 

The body is : 
            box.XXXX.XX -- Previously:
             ============================
and nothing else. 

The mail seems to be send at the same time of the back-up process. 

Mail-in-a-box version : 0.16

**Comment by JoshData** [comment] 2016-02-22 19:22
This is likely already fixed by https://github.com/mail-in-a-box/mailinabox/commit/8ea42847da25ef07b344d12c376840920134a0d2 which will be in the next update.

**Comment by smic77** [comment] 2016-02-22 19:38
Thanks

**Comment by frootmig** [comment] 2016-02-22 21:26
Just for the record: I'm not using domains with non ASCII characters.

Is is safe to apply the patch on my setup to test if it will solve the problem or might break this the upgrade path?

**Comment by JoshData** [comment] 2016-02-22 22:38
> Just for the record: I'm not using domains with non ASCII characters.

Ah, hmm, ok the commit message was wrong but I am pretty sure that fixed this issue.

> Is is safe to apply the patch on my setup to test if it will solve the problem or might break this the upgrade path?

Depends on how you did your initial setup. If you can, hang on a few days.

**Comment by benbyford** [comment] 2016-03-14 10:53
has this been fixed? it's quite painful recieveing status emails everyday, when nothing is actually wrong

**Comment by frootmig** [comment] 2016-03-14 17:39
I can confirm that this issue is fixed. There has been just one email after the mailinabox update and then no later emails, as nothing changed.

**Comment by smic77** [comment] 2016-03-14 22:53
I confirm also the issue is fixed. On the first night after the update,  I received a cumulative mail with all previous modifications and since then, not anymore except when changes are made or packages need to be updated, as frootmig has yet explained.

**Comment by JoshData** [comment] 2016-03-14 22:54
Thanks all.

**Closed by JoshData** 2016-03-14 22:54 UTC
Labels: bug
