### ISSUE TITLE
stty: standard input: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by stevetoza** [mail-in-a-box/mailinabox#361] opened 2015-03-22 17:11 UTC
Hello, 

When the install has completed the message 

    stty: standard input: Inappropriate ioctl for device

Appears with the MIAB information at the end. If you need any tests done for a fix let me know, more than happy.

Steve

**Comment by hnk** [comment] 2015-03-28 12:44
Duplicate of #354.

**Closed** 2015-03-28 13:33 UTC
