### ISSUE TITLE
I do not get some mail

### ISSUE THREAD

**Issue by arobase13** [mail-in-a-box/mailinabox#1137] opened 2017-04-03 12:43 UTC
Hello, after several months of use, I realize that when registering on sites, or buying online, sometimes I do not receive mail.

Is there any logs to check or other .... Have you ever encountered this type of problem?

Thank you for your help.

**Comment by tynie** [comment] 2017-04-03 13:18
Running my box about 6 month and never had problems like that. Maybe check your mail.log.

**Comment by biermeester** [comment] 2017-04-03 13:31
You can run `./management/maillogscan.py -gbv` to see what emails were blocked and/or greylisted.

**Comment by arobase13** [comment] 2017-04-03 13:35
Using username "root".
Authenticating with public key "rsa-key-20170403"
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-77-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Mon Apr  3 15:25:27 CEST 2017

  System load:  0.4               Processes:           127
  Usage of /:   4.5% of 97.92GB   Users logged in:     0
  Memory usage: 14%               IP address for eth0: 5.196.200.146
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/


WARNING: Security updates for your current Hardware Enablement Stack
ended on 2016-08-04:
 * http://wiki.ubuntu.com/1404_HWE_EOL

To upgrade to a supported (or longer-supported) configuration:

* Upgrade from Ubuntu 14.04 LTS to Ubuntu 16.04 LTS by running:
sudo do-release-upgrade

OR

* Switch to the current security-supported stack by running:
sudo apt-get install linux-image-generic-lts-xenial linux-generic-lts-xenial

and reboot your system.
Last login: Mon Apr  3 15:25:27 2017 from 181-144-190-109.dsl.ovh.fr
root@mail:~# vi /etc/ssh/ssh_config
root@mail:~# vi /etc/sshd/ssh_config
root@mail:~# vi /etc/ssh/sshd_config
root@mail:~# dir
create-cron.sh                    logs_update_03-03-2017-21:45.txt  test.sh
dead.letter                       log_uptime.txt                    update.sh
logs_update_03-03-2017-21:30.txt  mailinabox
logs_update_03-03-2017-21:40.txt  reboot.sh
root@mail:~# cd mailinabox/
root@mail:~/mailinabox# ./management/maillogscan.py -gbv
-bash: ./management/maillogscan.py: Aucun fichier ou dossier de ce type
root@mail:~/mailinabox# dir
CHANGELOG.md        CONTRIBUTING.md  ppa          setup  Vagrantfile
CODE_OF_CONDUCT.md  LICENSE          README.md    tests
conf                management       security.md  tools
root@mail:~/mailinabox# cd management/
root@mail:~/mailinabox/management# dir
auth.py                dns_update.py           ssl_certificates.py
backup.py              email_administrator.py  status_checks.py
csr_country_codes.tsv  mailconfig.py           templates
daemon.py              mail_log.py             utils.py
daily_tasks.sh         __pycache__             web_update.py
root@mail:~/mailinabox/management# ./maillog.py -gbv
-bash: ./maillog.py: Aucun fichier ou dossier de ce type
root@mail:~/mailinabox/management# ./mail_log.py -gbv
Ignoring received emails
Ignoring sent emails
Ignoring logins
Showing greylisted emails
Showing blocked emails
Scanning from 2017-04-03 15:34:12 back to 2017-04-03 00:00:00
Processing file /var/log/mail.log ...
Processing file /var/log/mail.log.1 ...
1940 Log lines scanned, 967 lines parsed in 0.20 seconds


Greylisted Email 2017-04-03 00:00:00 and 2017-04-03 15:34:12
════════════════════════════════════════════════════════════

 The following mail was greylisted, meaning the emails were temporarily
 rejected. Legitimate senders will try again within ten minutes.

                                  received sender delivered sending host
────────────────────────────────────────────────────────────────────────
────────────────────────────────────────────────────────────────────────
Totals:                                  0      0         0            0
root@mail:~/mailinabox/management#

**Comment by arobase13** [comment] 2017-04-15 09:44
Hello, I come back to you to solve this problem.
I bought TGV tickets (I am French) on the Ouigo site for not naming them, and I never received a confirmation email or even my electronic tickets on my mail mailbox, I know that I had encountered the same problem with other website, I absolutely want to use exclusively my e-mails. Mail server, but I am still constrained sometimes to use yahoo to receive this type of mail.

As a result a little bit off topic, in some web form, I often get invalid email address, the still forced to use a yahoo address, had you also this problem, can you bypass it?

I thank you in advance

**Comment by yeah** [comment] 2017-04-20 18:11
In the future, please use [the forum](https://discourse.mailinabox.email/) for usage related questions and reserve GitHub to discussing confirmed bugs or issues. This way, it will be easier for the developers of MIAB to push the project forward more efficiently. Thanks!

**Comment by JoshData** [comment] 2017-08-03 12:20
Closing because it's been a while. Feel free to reopen.

**Closed by JoshData** 2017-08-03 12:20 UTC
