### ISSUE TITLE
unexpected Z-Push download

### ISSUE THREAD

**Issue by soletan** [mail-in-a-box/mailinabox#1319] opened 2018-01-07 23:13 UTC
Tried a fresh install on a pristine host, but it failed obviously due to failed signature check on Z-Push install package. Is Z-Push broken or are their any revisions in deployment resulting in a different hash so mailinabox needs to adopt the latter?

Here comes the output of running installer (omitting the leading staff regarding IP addresses etc.):

```
Mail-in-a-Box Version:  v0.25

Updating system packages...
Installing system packages...
Initializing system random number generator...
Firewall is active and enabled on system startup
Installing nsd (DNS server)...
Installing Postfix (SMTP server)...
Installing Dovecot (IMAP server)...
Installing OpenDKIM/OpenDMARC...
Installing SpamAssassin...
Removing apache...
Installing Nginx (web server)...
Installing Roundcube (webmail)...
Installing Nextcloud (contacts/calendar)...
Nextcloud is already latest version
Installing Z-Push (Exchange/ActiveSync server)...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of http://download.z-push.org/final/2.3/z-push-2.3.8.tar.gz did not match expected checksum.
Found:
66b1613faef61590836682ff1a43d559827fe08b  /tmp/z-push.tar.gz

Expected:
aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb  /tmp/z-push.tar.gz
```

Tried running mailinabox again resulting in same issue.

**Comment by soletan** [comment] 2018-01-07 23:18
Obviously, there was a hotfix on 2.3.8: https://stash.z-hub.io/projects/ZP/repos/z-push/commits?until=refs%2Ftags%2F2.3.8

**Comment by soletan** [comment] 2018-01-07 23:19
Probable hotfix found here: https://discourse.mailinabox.email/t/z-push-installation-error/2737

**Comment by hachre** [comment] 2018-01-07 23:23
Duplicate of https://github.com/mail-in-a-box/mailinabox/issues/1304

**Closed** 2018-01-08 05:41 UTC
