### ISSUE TITLE
broken munin setup (404)

### ISSUE THREAD

**Issue by fiws** [mail-in-a-box/mailinabox#474] opened 2015-06-30 16:12 UTC
hi, i just updated my mailinabox setup. Sadly munin does not seem to work.

opening /admin/munin asks me for auth, then 404s.

Found the following stuff in the logs:

## munin-update.log
```
2015/06/30 12:05:01 [INFO]: Munin-update finished for node fiws.net;box.fiws.net (0.02 sec)
2015/06/30 12:05:01 [INFO] Reaping Munin::Master::UpdateWorker<fiws.net;box.fiws.net>.  Exit value/signal: 0/0
2015/06/30 12:05:01 [INFO]: Munin-update finished (0.05 sec)
2015/06/30 12:08:07 [INFO]: Starting munin-update
2015/06/30 12:08:07 [INFO] starting work in 4465 for box.fiws.net/127.0.0.1:4949.
2015/06/30 12:08:07 [WARNING] Config node box.fiws.net listed no services for box.fiws.net.  Please see http://munin-monitoring.org/wiki/FAQ_no_graphs for further information.
2015/06/30 12:08:07 [INFO]: Munin-update finished for node fiws.net;box.fiws.net (0.02 sec)
2015/06/30 12:08:07 [INFO] Reaping Munin::Master::UpdateWorker<fiws.net;box.fiws.net>.  Exit value/signal: 0/0
2015/06/30 12:08:07 [INFO]: Munin-update finished (0.06 sec)
```

## munin-node.log
```
2015/06/30-11:45:01 CONNECT TCP Peer: "[::ffff:127.0.0.1]:51714" Local: "[::ffff:127.0.0.1]:4949"
2015/06/30-11:50:01 CONNECT TCP Peer: "[::ffff:127.0.0.1]:51725" Local: "[::ffff:127.0.0.1]:4949"
2015/06/30-11:55:02 CONNECT TCP Peer: "[::ffff:127.0.0.1]:51876" Local: "[::ffff:127.0.0.1]:4949"
2015/06/30-11:58:35 Server closing!
Process Backgrounded
2015/06/30-11:58:57 Munin::Node::Server (type Net::Server::Fork) starting! pid(800)
Resolved [*]:4949 to [::]:4949, IPv6
Not including resolved host [0.0.0.0] IPv4 because it will be handled by [::] IPv6
Binding to TCP port 4949 on host :: with IPv6
2015/06/30-11:58:59 [800] Error output from fail2ban:
2015/06/30-11:58:59 [800] 	ERROR  Unable to contact server. Is it running?
2015/06/30-11:59:10 [800] Error output from ntp_states:
2015/06/30-11:59:10 [800] 	localhost: timed out, nothing received
2015/06/30-11:59:10 [800] 	***Request timed out
2015/06/30-12:00:01 CONNECT TCP Peer: "[::ffff:127.0.0.1]:46098" Local: "[::ffff:127.0.0.1]:4949"
2015/06/30-12:05:01 CONNECT TCP Peer: "[::ffff:127.0.0.1]:46167" Local: "[::ffff:127.0.0.1]:4949"
2015/06/30-12:08:07 CONNECT TCP Peer: "[::ffff:127.0.0.1]:46189" Local: "[::ffff:127.0.0.1]:4949"
2015/06/30-12:10:01 CONNECT TCP Peer: "[::ffff:127.0.0.1]:46207" Local: "[::ffff:127.0.0.1]:4949"
```

**Comment by macinjosh** [comment] 2015-06-30 22:07
I can confirm I am seeing the same behavior on v0.11b.

**Comment by nstanke** [comment] 2015-07-01 10:33
Seems like a binding issue. So you both have an IPv4 & IPv6 address provided?

**Comment by macinjosh** [comment] 2015-07-01 14:37
I do have IPv4 and IPv6 setup.

**Comment by nstanke** [comment] 2015-07-01 20:35
Hi,

Actually it seems to be a rewrite issue, you should be able to access Munin by opening `https://box.example.com/admin/munin/index.html`. I'm about to submit a fix for this.

**Comment by nstanke** [comment] 2015-07-05 13:30
I tried my best to resolve this issue, even after fixing `munin-check`s complaints no graphs are generated. Maybe we should consider #448 as an option.

**Comment by h8h** [comment] 2015-07-09 20:32
I solved this issue, hopefully it also solves the issue you have.
First `127.0.0.1` could not be resolved to my hostname `box.domain.tld` so he wouldn't generate any graphs. I did some researches on the www and found that there is a parameter called `use_node_name yes` ([use_node_name](http://munin-monitoring.org/wiki/use_node_name)). That uses also the node name, i think. 
After setting this option, I `su` as munin user and run the cron job.
* `su - munin --shell=/bin/bash`
* `munin-cron --debug` (debug for the nice output, to see whats going on)

I think you can wait 30 mins or whats the cron job is up to, but i have no time, i want to see the graphs and I want to see them now :-).

Ater fireing munin-cron up it genereates all the files in the folder `/var/cache/munin/www/`. Thats all, I think if it finally work for all miab users, we need only to change the `munin` config and put out some nice hint for the user: 'Please wait until the cronjob does it job and generate the graphs for you ...'

```
[box.domain.tld]
address 127.0.0.1
use_node_name yes
```

**Comment by fiws** [comment] 2015-07-09 20:45
@h8h thanks a lot. this fixed it. 
For anyone else applying this, some extra information:

* munin config is in `/etc/munin/munin.conf`
* `sudo su - munin --shell=/bin/bash` will actually let you switch to munin

**Comment by h8h** [comment] 2015-07-09 20:48
Thanks for the feedback. I'm glad I could help.
* yeah i edit this already,  thanks for pointing that out
* simply thanks :)

**Comment by fiws** [comment] 2015-07-09 23:39
without much work i could get my data in graphite/grafana now. :D

![screenshot from 2015-07-10 01-35-49](https://cloud.githubusercontent.com/assets/3409958/8609345/53cae176-26a4-11e5-9183-259acc9f949a.png)

**Closed** 2015-07-22 21:04 UTC

**Comment by JoshData** [comment] 2015-07-22 21:05
I believe I fixed this in the commit above.
