### ISSUE TITLE
Z-push has trouble saving to Sent folder with v0.14 update

### ISSUE THREAD

**Issue by ptimof** [mail-in-a-box/mailinabox#601] opened 2015-11-20 12:33 UTC
Seems like the latest version of Z-push may have a bug with writing to the Sent folder:

```
20/11/2015 07:15:57 [22224] [WARN] [user@example.com] BackendIMAP->getFolderIdFromImapId('SENT') = not initialized!
20/11/2015 07:15:57 [22224] [ERROR] [user@example.com] BackendIMAP->saveSentMessage(): The email could not be saved to Sent Items folder. Check your configuration.
```

There's some chatter about this in the Z-push issues list entry [#224](https://github.com/fmbiete/Z-Push-contrib/issues/224). I tried a `z-push-admin -a fixstates` and `z-push-admin -a resync -t email` as suggested in the entry, and no joy.

If I get some time this weekend, I'll try to dig deeper and see if it's just my existing account that has the problem, or if it seems to be system-wide.

**Comment by yodax** [comment] 2015-11-20 13:26
I have been spending some time on that as well. Haven't been able to track it down. I tried changing the name of the folder and had a look at the code. Couldn't find anything yet. 

Also the preview is still broken and sometimes you get recurring notifications. 

The upstream z-push library is missing card and caldav, so using that would lose some functionality. However it is more actively maintained. (https://stash.z-hub.io/projects/ZP/repos/z-push/browse)

**Comment by ptimof** [comment] 2015-11-20 14:07
I may downgrade (either MAIB or just Z-Push) if I can't figure out things this weekend. I'm not using card or caldav in Z-push, so in my case, it's not really a problem downgrading. Although I may just downgrade Z-push - I really like the `sa-learn` fix in MAIB v0.14 that doesn't unlearn when spam is thrown away... 😊

**Comment by yodax** [comment] 2015-11-20 14:46
Be carefull downgrading just zpush. The configuration has changed. I was also thinking of going back, but back porting the CC fix. 

However I usually prefer fixing the problems, these are quite time consuming issues.

**Comment by ptimof** [comment] 2015-11-20 14:52
That's a very good point - might be better for myself to go back to MIAB v0.13b, and just apply the `sa-learn` fix. Would love to actually help fix the Z-push problem, but I'll have to see how my time is this weekend. The day job keeps interfering with the fun work... 😎

**Comment by JoshData** [comment] 2016-02-01 17:53
Any updates here?

**Comment by yodax** [comment] 2016-02-01 18:40
I have stopped using zpush because of some other mime issues, however I think this pr should have solved it: https://github.com/mail-in-a-box/mailinabox/pull/668

**Comment by JoshData** [comment] 2016-02-20 01:07
Closing as likely fixed and not reproducible at this time anyway.

**Closed by JoshData** 2016-02-20 01:07 UTC
