### ISSUE TITLE
MiaB adopting incorrect hostname

### ISSUE THREAD

**Issue by DamonGant** [mail-in-a-box/mailinabox#778] opened 2016-03-31 13:26 UTC
This is an issue that has arisen after the DigitalOcean DNS outage. My mail server no longer reports as _emsar.innovandalism.eu_ as it is supposed to, but as _emsar.your-server.de_, which is a composite from the local hostname (emsar) and the hetzner default hostname. rDNS was and is set up properly.

To clarify, I use DO DNS, but Hetzner for hosting.

**Comment by JoshData** [comment] 2016-04-06 22:50
What does "reports" mean?

**Comment by DamonGant** [comment] 2016-04-07 06:52
Postfix Hostname. For instance, I got mail delivery status notifications from MAILER-DAEMON@emsar.your-server.de

**Comment by JoshData** [comment] 2016-05-19 22:46
Unfortunately I don't know what the issue is off-hand. I'm closing this here but feel free to start a discussion on the discussion forum.

**Closed by JoshData** 2016-05-19 22:46 UTC
