### ISSUE TITLE
ownCloud 9

### ISSUE THREAD

**Issue by itsazzad** [mail-in-a-box/mailinabox#764] opened 2016-03-21 15:58 UTC
Is it moving to ownCloud 9 soon?

**Comment by aspdye** [comment] 2016-03-21 16:11
Ref #514

**Comment by JoshHarmon** [comment] 2016-03-21 23:11
Worth noting is that my (separate) ownCloud box caused connection issues to CalDAV via OS X 10.11 when upgraded to 9.0. The reason for that is because they moved the iOS/OS X CalDAV URL from /remote.php/caldav/principals/user/name to /remote.php/dav/principals/user/name. I simply had to re-add the calendar account in the Advanced mode and manually set the URL.

OS X and iOS Contacts apps were unaffected, it seems.

**Comment by ponychicken** [comment] 2016-03-28 07:28
I would suggest doing the upgrade even though it should be replaced with something better on the longterm. The update fixes a number of stupid bugs (for example I cannot currently open a OwnCloud-created zip file on the Mac)

**Comment by ponychicken** [comment] 2016-03-28 07:29
Maybe it's best to wait until 9.0.1 is released which looks to be the fifth of April.

**Comment by aspdye** [comment] 2016-03-29 14:59
We wait until all CardDAV and CalDAV Features are well implemented. 9.0 is a great release, but 9.0.1 of ownCloud Core and 1.1 on Calendar are necessary updates **before** we implement this into MiaB-Instances. :wink: Otherwise, there would be some problems with CalDAV and CardDAV shares :grin: 

ownCloud Calendar 1.1 will be released on 12.04. so I think we can release Mail-in-a-Box with ownCloud 9.0 at the end of 04/2016 :stuck_out_tongue_winking_eye:

**Comment by anoma** [comment] 2016-03-29 16:56
As anecdotal evidence of why @aspdye is spot on, I tried to update the cardav plugin on my docker install here and it responded with an error. Google provided the answer that the problem is core and fixed in 9.0.1.

**Comment by aspdye** [comment] 2016-04-24 12:45
☝️test, develop and enjoy 😉

**Comment by JoshData** [comment] 2016-05-22 11:46
Let's take this conversation back to #514. The answer to the original question is: We don't know.

**Closed by JoshData** 2016-05-22 11:46 UTC
