### ISSUE TITLE
Roundcube reply-to address not set correctly

### ISSUE THREAD

**Issue by zoof** [mail-in-a-box/mailinabox#595] opened 2015-11-13 15:43 UTC
With my prior experience with Roundcube, the reply-to address would be set to the sending alias's address.  I've just noticed that when I receive an email sent via my MiaB Roundcube installation, when I reply using Thunderbird, the "To:" address is blank.  I think this is a Roundcube configuration issue as mail from the MiaB installation using other email clients work as expected.

**Comment by JoshData** [comment] 2016-08-22 22:56
Has anyone else encountered this?

**Comment by stan3** [comment] 2016-09-09 20:39
Can't reproduce this - just tried emailing a non MiaB account from MiaB's Roundcube and then replying in Thunderbird.  The To field is populated as expected.

**Comment by JoshData** [comment] 2016-09-10 11:47
Thanks. Closing since this is a very old one.

**Closed by JoshData** 2016-09-10 11:47 UTC
Labels: bug
