### ISSUE TITLE
z-push hash sum mismatch

### ISSUE THREAD

**Issue by johngit7** [mail-in-a-box/mailinabox#1320] opened 2018-01-08 11:54 UTC
Error while installing.

```
Installing Z-Push (Exchange/ActiveSync server)...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of http://download.z-push.org/final/2.3/z-push-2.3.8.tar.gz did not match expected checksum.
Found:
66b1613faef61590836682ff1a43d559827fe08b  /tmp/z-push.tar.gz

Expected:
aae5093212ac0b7d8bf2d79fd5b87ca5bbf091cb  /tmp/z-push.tar.gz
```

**Comment by yodax** [comment] 2018-01-08 11:56
Hi thanks for posting. This is a duplicate of: https://github.com/mail-in-a-box/mailinabox/issues/1304

There's a fix for it in master, with instructions on how to install in the other issue.

**Closed by yodax** 2018-01-08 11:56 UTC
