### ISSUE TITLE
Race condition between backups and status checks change check - Connection refused

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#381] opened 2015-04-14 07:49 UTC
I received this email this morning from MIAB. As far as I can tell the system was and is working perfectly. I can only assume this is some kind of false positive or race condition with a scheduled service restart e.g. backup.

```
System -- Previously:
=====================
✓  All system services are running.

System -- Currently:
====================
✖  Dovecot LMTP LDA is not running ([Errno 111] Connection refused; 
   port 10026).
✖  Sieve (dovecot) is not running ([Errno 111] Connection refused; 
   port 4190).
✖  IMAPS (dovecot) is not running ([Errno 111] Connection refused; 
   port 993).
```

**Comment by haroldus-** [comment] 2015-04-14 11:09
I got the same message about half an hour ago. ?

**Comment by JoshData** [comment] 2015-04-14 11:11
Me too. It's definitely a race condition with the backup.

**Comment by JoshData** [comment] 2015-04-14 11:12
...... Although odd that we all received it the first time today.

**Comment by haroldus-** [comment] 2015-04-15 12:09
new message from about an hour and 15 minutes ago:
System -- Previously:
=====================
✖  Dovecot LMTP LDA is not running ([Errno 111] Connection refused; 
   port 10026).
✖  Sieve (dovecot) is not running ([Errno 111] Connection refused; 
   port 4190).
✖  IMAPS (dovecot) is not running ([Errno 111] Connection refused; 
   port 993).

System -- Currently:
====================
✓  All system services are running.

**Comment by benschumacher** [comment] 2015-04-16 02:05
I've seen this, too. Could it be longer duplicity run due to cleanup?

**Comment by dhpiggott** [comment] 2015-04-16 08:42
I feel I should comment on this, though I've not seen the issue myself*.

If the hypothesis is that these happen because of longer backup runs, it might help if everyone who has seen the issue could state what commit they have deployed (or just whether it includes the new GPG encrypted backup system), and include the cron output of the backup job (if you have an alias set up and so do receive the output).

Deploying from a commit that includes the new GPG encrypted backup system likely would/does trigger this (except perhaps on nearly empty boxes), because the first backup that runs after deploying it will always be a full backup (for most people the only other time a full backup will have run will have been after first installing, which for most will likely have been before the email status check output feature was added - and a race with only one competitor isn't really a race - plus many boxes may still have been nearly empty at such times).

So presuming we've all upgraded to GPG encrypted backups, that would have been the trigger of the full backup, but it's not the root cause of the race condition; that I see as an issue that was waiting to happen because the status check cron job and the backup cron job only get configured to run daily - the exact timing is left to cron itself, which typically means they do run at the same time.

I guess a really trivial fix would be to make it so one runs e.g. an hour after the other, and I guess that would work for all intents and purposes. Or perhaps we could/should serialise them - run the status checks first and then do backups, all triggered by one job?

*the simple explanation for this is that I manually triggered my full backup rather than waiting for cron to trigger it.

**Comment by JoshData** [comment] 2015-04-16 11:38
I have two boxes, one at v0.08 and one with the new duplicity changes. They both had this happen (on different days though).

From `/etc/crontab`:

    25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

`run-parts` executes the scripts serially in lexical sort order. (`anacron` is not installed.)

I'm guessing that it's just that dovecot is taking a few moments to start after the backup script brings it back online and it's not ready by the time the status checks script runs. This could be fixed by adding a delay at the end of the backup script --- it could wait for dovecot to appear to be running again by using the same sort of socket test that the status checks does.

**Comment by dhpiggott** [comment] 2015-04-17 08:19
Thanks for the explanation re. run-parts running things in lexical order. I should be more careful in identifying and questioning my assumptions!

**Closed** 2015-04-29 21:07 UTC
