### ISSUE TITLE
Pango-WARNING during installation from munin

### ISSUE THREAD

**Issue by thejaswip** [mail-in-a-box/mailinabox#495] opened 2015-07-15 15:01 UTC
I have frequently seen this error during the initial installation and also , after "reinstallation" by doing mailinabox command line again . 

(process:5723): Pango-WARNING **: error opening config file '/root/.config/pango/pangorc': Permission denied

**Comment by JoshData** [comment] 2015-07-16 12:48
Yeah it's something coming from munin. It's not causing problems for me, but I don't know the cause.

**Comment by thejaswip** [comment] 2015-07-16 13:31
I have reached it is being caused by
sudo -u munin munin-cron

**Comment by h8h** [comment] 2015-07-24 17:52
Its something Xorg related. But there no Xorg on the server, so that should be O.K.

**Comment by JoshData** [comment] 2015-08-23 16:56
I think fixed by 6c71abbb09313dde279968e86cdfa43a9675d69e.

**Closed by JoshData** 2015-08-23 16:56 UTC
