### ISSUE TITLE
WWW prefix handling

### ISSUE THREAD

**Issue by nstanke** [mail-in-a-box/mailinabox#321] opened 2015-02-12 16:00 UTC
Additonal domains added to MiaB are only accessible under:

- http://example.com
- https://example.com

Not working:

- http://www.example.com redirects to https://box.hostname.com
- https://www.example.com uses box.hostname.com SSL certificate, although a valid certificate for www.example.com is provided.

Is this behavior intentional?

**Comment by JoshData** [comment] 2015-02-12 19:58
* The HTTP->HTTPS redirect is by design. We should be secure all the time.
* If the wrong certificate is being used, you may need to run `tools/web_update` to force a refresh of the configuration files. Or it's a bug.

**Comment by JoshData** [comment] 2015-02-12 19:59
.... But note that it'll grab the box.___ certificate if that certificate claims it is also good for other domains (e.g. wildcard/multi-domain certs). So in those cases it'll be the box.___ cert, but it will work fine.

**Comment by nstanke** [comment] 2015-02-12 21:14
I ran ``tools/web_update`` aswell as the whole setup script multiple times. The control panel says that ``hostname.com - Signed & valid. Using multi/wildcard certificate of box.hostname.com`` 

The newly added domain (example.com) says ``Signed & valid. The certificate expires in 365 days on 02/12/16.`` 

Coudn't we add a Nginx rewrite to non-www?

**Comment by JoshData** [comment] 2015-02-17 00:53
Oh I see. The box doesn't know it's supposed to be serving `www` at all, so nginx is serving the default server config, which results in a different cert.

For now, the way to do this is to add a dummy mail alias on the www subdomain. But it won't issue the redirect -- it'll just serve the same site. Then you could use the undocumented redirects feature to add a redirect.

We serve default DNS for www, so we might as well serve a default website or default redirect. I just committed a fix 3c50c9a18b9e02708295d225ca11cf70002c5ecb to get the SSL certificate right. It'll be a little trickier to get the rest working though. Instead of serving default www DNS entries, we should just treat a default `www` like other domain names we serve, but put a redirect in instead of a website.

**Closed** 2015-06-04 12:19 UTC
