### ISSUE TITLE
No screenshots in readme?

### ISSUE THREAD

**Issue by Gameboy24** [mail-in-a-box/mailinabox#645] opened 2015-12-30 23:50 UTC
It would be nice to have some screenshots of the web interface in the readme.

**Comment by aspdye** [comment] 2015-12-30 23:54
Duplicate of #181

**Comment by JoshData** [comment] 2016-01-03 14:02
Right. Trying to not duplicate effort -- there are screenshots on the website. Please reopen an issue at https://github.com/mail-in-a-box/mailinabox.email if you want to update the screenshots there.

**Closed by JoshData** 2016-01-03 14:02 UTC
