### ISSUE TITLE
Delayed Mail (still being retried) and Undelivered Mail Returned to Sender

### ISSUE THREAD

**Issue by arobase13** [mail-in-a-box/mailinabox#1194] opened 2017-06-20 14:34 UTC
Hello,
After this problem last week or by sending a very important mail I first receive a mail then a second, but impossible to send it to my recipient.

I registered on the forum, account blocked immediately, then unlocked then again blocked, in short, I'm lost.

Copy below of mail received

> This is the mail system at host mail.mydomain.

####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 3 hour(s).
It will be retried until it is 2 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<clerc@xxxxx.com>: host mail.xxxxx.com[80.11.178.84]
    refused to talk to me: 554 5.7.1 You are not allowed to connect.

Reporting-MTA: dns; mail.mydomain
X-Postfix-Queue-ID: 4A1555F826
X-Postfix-Sender: rfc822; xxxxx@mydomain
Arrival-Date: Thu, 15 Jun 2017 07:45:16 +0200 (CEST)

Final-Recipient: rfc822; clerc@xxxxx.com
Original-Recipient: rfc822;clerc@xxxxx.com
Action: delayed
Status: 4.7.1
Remote-MTA: dns; mail.xxxxx.com
Diagnostic-Code: smtp; 554 5.7.1 You are not allowed to connect.
Will-Retry-Until: Sat, 17 Jun 2017 07:45:16 +0200 (CEST)

Return-Path: <xxxxx@mydomain>
Received: from authenticated-user (mail.mydomain [5.196.200.146])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by mail.mydomain (Postfix) with ESMTPSA id 4A1555F826
	for <clerc@xxxxx.com>; Thu, 15 Jun 2017 07:45:16 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=mydomain; s=mail;
	t=1497505516; bh=f5lxgNol+WDIaRci4UzMe+2V9EpFAzhtP+AeBHXdvzg=;
	h=Subject:References:To:From:Date:In-Reply-To:From;
	b=qRKeffPYqmXitYMVpvsLhzCd8r2H2e4Yg1PhLYiG6OVprRuiouRh2H1AAFbMkil5Y
	 MHZIdE+2bnrPhgKhnuoq2nGKUFqT12CMytJuMT3HJF5Q4maXiM5PnuQ6z9JTH/iFES
	 XbDkk53BV7UpMtGHEwYo5QMPrfHMR8HV/N0o6fRECWzRoCzu18rpy7TIwGkrvF0Owe
	 rCztN+p0q4gqCRXeD7rZGseEnq/PRE4f77bRfD/dqcgUpRQ1Ug03JaTSrUqINsyFtI
	 1JuUH5ffpQFvj3JsUKpvfIwNfqemLxllsHxLe+fSHxUVTEJub0V8ukSE9b2Zu1pUvq
	 L2h65lq/oRxdw==
Subject: Flat lease group Romero
References: <20170614171013.AAC78608E7@mail.mydomain>
To: =?UTF-8?Q?Clerc_1_-_SCP_Gr=c3=a9gori_&_Terrier?=
 <clerc@xxxxx.com>
From: Manuel Romero <xxxxx@mydomain>
X-Forwarded-Message-Id: <20170614171013.AAC78608E7@mail.mydomain>
Message-ID: <8ca613ee-257d-e1de-89c8-9d0468ed514f@mydomain>
Date: Thu, 15 Jun 2017 07:45:16 +0200
MIME-Version: 1.0
In-Reply-To: <20170614171013.AAC78608E7@mail.mydomain>
Content-Type: multipart/alternative;
 boundary="------------09C61261EAD27EAF93E16384"
Content-Language: fr

> 

and

> This is the mail system at host mail.mydomain.fr.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<clerc@xxxxx.com>: host mail.xxxxx.com[80.11.178.84]
    refused to talk to me: 554 5.7.1 You are not allowed to connect.

Reporting-MTA: dns; mail.mydomain.fr
X-Postfix-Queue-ID: 4A1555F826
X-Postfix-Sender: rfc822; xxxxx@mydomain.fr
Arrival-Date: Thu, 15 Jun 2017 07:45:16 +0200 (CEST)

Final-Recipient: rfc822; clerc@xxxxx.com
Original-Recipient: rfc822;clerc@xxxxx.com
Action: failed
Status: 4.7.1
Remote-MTA: dns; mail.xxxxx.com
Diagnostic-Code: smtp; 554 5.7.1 You are not allowed to connect.

ForwardedMessage.eml
Sujet : 
Flat lease group Romero
De : 
xxxxxxx<xxxxx@mydomain.fr>
Date : 
15/06/2017 07:45
Pour : 
Clerc 1 - destination <clerc@xxxxx.com>
hfhffhfhf
jfjfjfjjfjfjf
kffkfkfkfk

        

This is the mail system at host mail.mydomain.fr.

####################################################################
# THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. #
####################################################################

Your message could not be delivered for more than 3 hour(s).
It will be retried until it is 2 day(s) old.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<clerc@xxxxx.com>: host mail.xxxxx.com[80.11.178.84]
    refused to talk to me: 554 5.7.1 You are not allowed to connect.

      

        

Reporting-MTA: dns; mail.mydomain.fr
X-Postfix-Queue-ID: 5996D5F826
X-Postfix-Sender: rfc822; xxxxx@mydomain.fr
Arrival-Date: Mon, 12 Jun 2017 18:03:31 +0200 (CEST)

Final-Recipient: rfc822; clerc@xxxxx.com
Original-Recipient: rfc822;clerc@xxxxx.com
Action: delayed
Status: 4.7.1
Remote-MTA: dns; mail.xxxxx.com
Diagnostic-Code: smtp; 554 5.7.1 You are not allowed to connect.
Will-Retry-Until: Wed, 14 Jun 2017 18:03:31 +0200 (CEST)

      

        

Return-Path: <xxxxx@mydomain.fr>
Received: from authenticated-user (mail.mydomain.fr [5.196.200.146])
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(No client certificate requested)
	by mail.mydomain.fr (Postfix) with ESMTPSA id 5996D5F826
	for <clerc@xxxxx.com>; Mon, 12 Jun 2017 18:03:31 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=mydomain.fr; s=mail;
	t=1497283412; bh=DdCs34A/uzIIeoXOQqmzpBohze5RoFu+XGW//UpI1BI=;
	h=Subject:To:References:From:Date:In-Reply-To:From;
	b=oMUQLN/4cq890CD/jSgio0kp9RHvZ8qP0QqRKMkk9H1FzkxlFTPX2eIQFcWmwRo4C
	 6ksXko8e0Lm2ybDiT1h5QuzYUUGt5G4Wi+Mwq5rePKBzum5Ea86MqcffSTJDVgQV/f
	 OqTBnoZHpyrwABQhD8b1h771AbZRHa0bSMcvQ9/OSTeUtxNDayTntpXUudmEg4PY2F
	 uZYAVAB1KuqtsM6mXXy8HD1q3xEq58kTuLW8BJIjb3GgKjYOPJVBu73h3Y2c+617G2
	 k8vwbdWqFoEtmwP4eg7t2lhA2BBPEcqQQCaQa6z8/4pCZ7G0LG5p4nYT7Jb2h1Ndqu
	 wXIpGT6CdxoXg==
Subject: =?UTF-8?Q?DOSSIER_N=c2=b0_45214_Virement_250_=e2=82=ac?=
To: =?UTF-8?Q?Clerc_1_-_SCP_Gr=c3=a9gori_&_Terrier?=
 <clerc@xxxxx.com>
References: <-1864266878.1484755487633.JavaMail.javamailuser@localhost>
 <F9C2AD10-D752-4DBD-9F74-D09F8A692583@gmx.fr>
 <E62DDCB8FA000140AF202573AF664F5DF1525170@SERVEURSBS2011.xxxxx.local>
From: Manuel Romero <xxxxx@mydomain.fr>
Message-ID: <dbc7d77b-dfc9-2c55-4d6b-a8fdec53e1d5@mydomain.fr>
Date: Mon, 12 Jun 2017 18:03:31 +0200
MIME-Version: 1.0
In-Reply-To: <E62DDCB8FA000140AF202573AF664F5DF1525170@SERVEURSBS2011.xxxxx.local>
Content-Type: text/plain; charset=utf-8; format=flowed
Content-Transfer-Encoding: 8bit
Content-Language: fr

      

hghfghhfghghghghghghg
hjfjhfjjfjfjfjjfjfjfjf
hfhfhfhfhfhhfhfhfhfhfhf
-------- Message transféré --------
Sujet : 	Undelivered Mail Returned to Sender
Date : 	Wed, 14 Jun 2017 19:10:13 +0200 (CEST)
De : 	Mail Delivery System <MAILER-DAEMON@mail.mydomain.fr.fr>
Pour : 	xxxxx@mydomain.fr

This is the mail system at host mail.mydomain.fr.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<clerc@xxxxx.com>: host mail.xxxxx.com[80.11.178.84]
    refused to talk to me: 554 5.7.1 You are not allowed to connect.

>

**Comment by yodax** [comment] 2017-06-20 14:59
The remote doesn't allow you to connect. 

554 5.7.1 You are not allowed to connect.

Check if your ipaddres is blacklisted.

**Comment by arobase13** [comment] 2017-06-20 15:13
My ip address is not blacklisted

**Comment by yodax** [comment] 2017-06-20 15:36
Can you mail with other people? If so, it seems the problem is on the receiving end. You could try and send them an email from an alternate provider (for instance gmail).

**Comment by arobase13** [comment] 2017-06-21 07:26
Sure enough I went through another provider to send my mail, and actually I have this problem with that person.

**Comment by arobase13** [comment] 2017-06-23 08:51
Hello,
My correspondent received my mail via Yahoo. By cons from my server impossible, can we really do without providers such as Yahoo or Gmail and use exclusively our own mail server?

Is this due to an anti-spam protection of the recipient's server?

Another question can be proposed improvements to the teams?

**Comment by JoshData** [comment] 2017-08-03 12:11
There aren't simple answers to your questions (and I'm not sure I understood what you were asking). I'm going to close this issue. Feel free to open a new issue with a specific question.

**Closed by JoshData** 2017-08-03 12:11 UTC

**Comment by luizoliveira23** [comment] 2017-10-27 12:42
Pessoal to enfrentando um problema um pouco chato em minha empresa, montei um servidor zpanel completo, tudo funcionando normalmente, site, banco de dados. o problema aparece no servidor de e-mail, envio para qualquer domínio exceto gmail.com, no entando recebo e-mail do gmail.com. Alguém pode dar uma luz e me ajudar com esse problema.
